<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="10" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="90331" started-at="2019-05-30T09:42:02Z" finished-at="2019-05-30T09:43:33Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="90331" started-at="2019-05-30T09:42:02Z" finished-at="2019-05-30T09:43:33Z">
      <class name="com.qa.testcases.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="setUp" is-config="true" duration-ms="9719" started-at="2019-05-30T15:12:02Z" finished-at="2019-05-30T15:12:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateTitle()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="validateTitle" duration-ms="107" started-at="2019-05-30T15:12:12Z" finished-at="2019-05-30T15:12:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ShopCartt > Administration panel (PrestaShopâ)] but found [ShopCartt > Administration panel (PrestaShop™)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ShopCartt > Administration panel (PrestaShopâ)] but found [ShopCartt > Administration panel (PrestaShop™)]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.qa.testcases.LoginPageTest.validateTitle(LoginPageTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="tearDown" is-config="true" duration-ms="2108" started-at="2019-05-30T15:12:13Z" finished-at="2019-05-30T15:12:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="setUp" is-config="true" duration-ms="7075" started-at="2019-05-30T15:12:15Z" finished-at="2019-05-30T15:12:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validatePrestaLogo()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="validatePrestaLogo" duration-ms="92" started-at="2019-05-30T15:12:22Z" finished-at="2019-05-30T15:12:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePrestaLogo -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="tearDown" is-config="true" duration-ms="160" started-at="2019-05-30T15:12:22Z" finished-at="2019-05-30T15:12:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="setUp" is-config="true" duration-ms="5674" started-at="2019-05-30T15:12:22Z" finished-at="2019-05-30T15:12:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validatePrestaLogoText()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="validatePrestaLogoText" duration-ms="81" started-at="2019-05-30T15:12:28Z" finished-at="2019-05-30T15:12:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePrestaLogoText -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="tearDown" is-config="true" duration-ms="154" started-at="2019-05-30T15:12:28Z" finished-at="2019-05-30T15:12:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="setUp" is-config="true" duration-ms="7856" started-at="2019-05-30T15:12:28Z" finished-at="2019-05-30T15:12:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validateCurrentUrl()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="validateCurrentUrl" duration-ms="19" started-at="2019-05-30T15:12:36Z" finished-at="2019-05-30T15:12:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCurrentUrl -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="tearDown" is-config="true" duration-ms="2079" started-at="2019-05-30T15:12:36Z" finished-at="2019-05-30T15:12:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="setUp" is-config="true" duration-ms="6190" started-at="2019-05-30T15:12:38Z" finished-at="2019-05-30T15:12:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validateTextBelowLogo()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="validateTextBelowLogo" duration-ms="87" started-at="2019-05-30T15:12:44Z" finished-at="2019-05-30T15:12:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTextBelowLogo -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="tearDown" is-config="true" duration-ms="137" started-at="2019-05-30T15:12:44Z" finished-at="2019-05-30T15:12:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="setUp" is-config="true" duration-ms="6898" started-at="2019-05-30T15:12:45Z" finished-at="2019-05-30T15:12:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validateEmailLable()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="validateEmailLable" duration-ms="94" started-at="2019-05-30T15:12:51Z" finished-at="2019-05-30T15:12:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateEmailLable -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="tearDown" is-config="true" duration-ms="129" started-at="2019-05-30T15:12:52Z" finished-at="2019-05-30T15:12:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="setUp" is-config="true" duration-ms="6170" started-at="2019-05-30T15:12:52Z" finished-at="2019-05-30T15:12:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateEmailPlaceholder()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="validateEmailPlaceholder" duration-ms="61" started-at="2019-05-30T15:12:58Z" finished-at="2019-05-30T15:12:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [test@example.com] but found [? test@example.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [test@example.com] but found [? test@example.com]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.qa.testcases.LoginPageTest.validateEmailPlaceholder(LoginPageTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateEmailPlaceholder -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="tearDown" is-config="true" duration-ms="113" started-at="2019-05-30T15:12:58Z" finished-at="2019-05-30T15:12:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="setUp" is-config="true" duration-ms="10955" started-at="2019-05-30T15:12:59Z" finished-at="2019-05-30T15:13:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validatePasswordPlaceholder()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="validatePasswordPlaceholder" duration-ms="59" started-at="2019-05-30T15:13:09Z" finished-at="2019-05-30T15:13:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [? Password] but found [? Password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [? Password] but found [? Password]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.qa.testcases.LoginPageTest.validatePasswordPlaceholder(LoginPageTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePasswordPlaceholder -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="tearDown" is-config="true" duration-ms="123" started-at="2019-05-30T15:13:10Z" finished-at="2019-05-30T15:13:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="setUp" is-config="true" duration-ms="7465" started-at="2019-05-30T15:13:10Z" finished-at="2019-05-30T15:13:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validateBlankEmailPassword()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="validateBlankEmailPassword" duration-ms="2403" started-at="2019-05-30T15:13:18Z" finished-at="2019-05-30T15:13:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateBlankEmailPassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="tearDown" is-config="true" duration-ms="211" started-at="2019-05-30T15:13:20Z" finished-at="2019-05-30T15:13:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="setUp" is-config="true" duration-ms="10070" started-at="2019-05-30T15:13:20Z" finished-at="2019-05-30T15:13:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validateBlankEmailAndValidPassword()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="validateBlankEmailAndValidPassword" duration-ms="2361" started-at="2019-05-30T15:13:30Z" finished-at="2019-05-30T15:13:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateBlankEmailAndValidPassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.LoginPageTest@6debcae2]" name="tearDown" is-config="true" duration-ms="134" started-at="2019-05-30T15:13:33Z" finished-at="2019-05-30T15:13:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.testcases.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
